# Generated by Django 2.1.7 on 2019-02-14 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20190214_1341'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='products',
        ),
        migrations.AddField(
            model_name='product',
            name='history',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.Customer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='customers', to='home.Product'),
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='home.Brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ManyToManyField(blank=True, related_name='products', to='home.Category'),
        ),
    ]
