# Generated by Django 2.1.7 on 2019-02-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20190214_1350'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='history',
        ),
        migrations.AddField(
            model_name='product',
            name='history',
            field=models.ManyToManyField(blank=True, related_name='products', to='home.Customer'),
        ),
    ]
