# Generated by Django 2.1.7 on 2019-02-14 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20190214_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='friends',
            field=models.ManyToManyField(blank=True, related_name='_friends', to='home.Customer'),
        ),
    ]
