# Generated by Django 2.1.7 on 2019-02-14 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_customer_friends'),
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('contact_no', models.IntegerField()),
                ('brand', models.ManyToManyField(related_name='stores', to='home.Brand')),
                ('customers', models.ManyToManyField(related_name='stores', to='home.Customer')),
            ],
        ),
    ]
