# Generated by Django 2.1.7 on 2019-02-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='customers',
            field=models.ManyToManyField(related_name='brands', to='home.Customer'),
        ),
    ]
